name: Docker

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build -t munt-node-docker .